// Copyright © 2025 Colden Cullen
// SPDX-License-Identifier: MIT

// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/task (interfaces: Executor,SessionManager)
//
// Generated by this command:
//
//	mockgen -destination task_mock.go -package test -copyright_file ../license-header.txt -typed ../pkg/task Executor,SessionManager
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	reflect "reflect"

	task "go.bonk.build/pkg/task"
	gomock "go.uber.org/mock/gomock"
)

// MockExecutor is a mock of Executor interface.
type MockExecutor[Params any] struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorMockRecorder[Params]
	isgomock struct{}
}

// MockExecutorMockRecorder is the mock recorder for MockExecutor.
type MockExecutorMockRecorder[Params any] struct {
	mock *MockExecutor[Params]
}

// NewMockExecutor creates a new mock instance.
func NewMockExecutor[Params any](ctrl *gomock.Controller) *MockExecutor[Params] {
	mock := &MockExecutor[Params]{ctrl: ctrl}
	mock.recorder = &MockExecutorMockRecorder[Params]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutor[Params]) EXPECT() *MockExecutorMockRecorder[Params] {
	return m.recorder
}

// Execute mocks base method.
func (m *MockExecutor[Params]) Execute(ctx context.Context, tsk *task.Task[Params], result *task.Result) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, tsk, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockExecutorMockRecorder[Params]) Execute(ctx, tsk, result any) *MockExecutorExecuteCall[Params] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockExecutor[Params])(nil).Execute), ctx, tsk, result)
	return &MockExecutorExecuteCall[Params]{Call: call}
}

// MockExecutorExecuteCall wrap *gomock.Call
type MockExecutorExecuteCall[Params any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutorExecuteCall[Params]) Return(arg0 error) *MockExecutorExecuteCall[Params] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutorExecuteCall[Params]) Do(f func(context.Context, *task.Task[Params], *task.Result) error) *MockExecutorExecuteCall[Params] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutorExecuteCall[Params]) DoAndReturn(f func(context.Context, *task.Task[Params], *task.Result) error) *MockExecutorExecuteCall[Params] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Name mocks base method.
func (m *MockExecutor[Params]) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockExecutorMockRecorder[Params]) Name() *MockExecutorNameCall[Params] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockExecutor[Params])(nil).Name))
	return &MockExecutorNameCall[Params]{Call: call}
}

// MockExecutorNameCall wrap *gomock.Call
type MockExecutorNameCall[Params any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutorNameCall[Params]) Return(arg0 string) *MockExecutorNameCall[Params] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutorNameCall[Params]) Do(f func() string) *MockExecutorNameCall[Params] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutorNameCall[Params]) DoAndReturn(f func() string) *MockExecutorNameCall[Params] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSessionManager is a mock of SessionManager interface.
type MockSessionManager struct {
	ctrl     *gomock.Controller
	recorder *MockSessionManagerMockRecorder
	isgomock struct{}
}

// MockSessionManagerMockRecorder is the mock recorder for MockSessionManager.
type MockSessionManagerMockRecorder struct {
	mock *MockSessionManager
}

// NewMockSessionManager creates a new mock instance.
func NewMockSessionManager(ctrl *gomock.Controller) *MockSessionManager {
	mock := &MockSessionManager{ctrl: ctrl}
	mock.recorder = &MockSessionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionManager) EXPECT() *MockSessionManagerMockRecorder {
	return m.recorder
}

// CloseSession mocks base method.
func (m *MockSessionManager) CloseSession(ctx context.Context, sessionId task.SessionId) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseSession", ctx, sessionId)
}

// CloseSession indicates an expected call of CloseSession.
func (mr *MockSessionManagerMockRecorder) CloseSession(ctx, sessionId any) *MockSessionManagerCloseSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSession", reflect.TypeOf((*MockSessionManager)(nil).CloseSession), ctx, sessionId)
	return &MockSessionManagerCloseSessionCall{Call: call}
}

// MockSessionManagerCloseSessionCall wrap *gomock.Call
type MockSessionManagerCloseSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionManagerCloseSessionCall) Return() *MockSessionManagerCloseSessionCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionManagerCloseSessionCall) Do(f func(context.Context, task.SessionId)) *MockSessionManagerCloseSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionManagerCloseSessionCall) DoAndReturn(f func(context.Context, task.SessionId)) *MockSessionManagerCloseSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// OpenSession mocks base method.
func (m *MockSessionManager) OpenSession(ctx context.Context, session task.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// OpenSession indicates an expected call of OpenSession.
func (mr *MockSessionManagerMockRecorder) OpenSession(ctx, session any) *MockSessionManagerOpenSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenSession", reflect.TypeOf((*MockSessionManager)(nil).OpenSession), ctx, session)
	return &MockSessionManagerOpenSessionCall{Call: call}
}

// MockSessionManagerOpenSessionCall wrap *gomock.Call
type MockSessionManagerOpenSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionManagerOpenSessionCall) Return(arg0 error) *MockSessionManagerOpenSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionManagerOpenSessionCall) Do(f func(context.Context, task.Session) error) *MockSessionManagerOpenSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionManagerOpenSessionCall) DoAndReturn(f func(context.Context, task.Session) error) *MockSessionManagerOpenSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
