// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: bonk/v0/executor.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenSessionRequest struct {
	state                           protoimpl.MessageState                    `protogen:"opaque.v1"`
	xxx_hidden_SessionId            *string                                   `protobuf:"bytes,1,opt,name=session_id,json=sessionId"`
	xxx_hidden_WorkspaceDescription isOpenSessionRequest_WorkspaceDescription `protobuf_oneof:"workspace_description"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *OpenSessionRequest) Reset() {
	*x = OpenSessionRequest{}
	mi := &file_bonk_v0_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionRequest) ProtoMessage() {}

func (x *OpenSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bonk_v0_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OpenSessionRequest) GetSessionId() string {
	if x != nil {
		if x.xxx_hidden_SessionId != nil {
			return *x.xxx_hidden_SessionId
		}
		return ""
	}
	return ""
}

func (x *OpenSessionRequest) GetLocal() *OpenSessionRequest_WorkspaceDescriptionLocal {
	if x != nil {
		if x, ok := x.xxx_hidden_WorkspaceDescription.(*openSessionRequest_Local); ok {
			return x.Local
		}
	}
	return nil
}

func (x *OpenSessionRequest) SetSessionId(v string) {
	x.xxx_hidden_SessionId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *OpenSessionRequest) SetLocal(v *OpenSessionRequest_WorkspaceDescriptionLocal) {
	if v == nil {
		x.xxx_hidden_WorkspaceDescription = nil
		return
	}
	x.xxx_hidden_WorkspaceDescription = &openSessionRequest_Local{v}
}

func (x *OpenSessionRequest) HasSessionId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OpenSessionRequest) HasWorkspaceDescription() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_WorkspaceDescription != nil
}

func (x *OpenSessionRequest) HasLocal() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_WorkspaceDescription.(*openSessionRequest_Local)
	return ok
}

func (x *OpenSessionRequest) ClearSessionId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_SessionId = nil
}

func (x *OpenSessionRequest) ClearWorkspaceDescription() {
	x.xxx_hidden_WorkspaceDescription = nil
}

func (x *OpenSessionRequest) ClearLocal() {
	if _, ok := x.xxx_hidden_WorkspaceDescription.(*openSessionRequest_Local); ok {
		x.xxx_hidden_WorkspaceDescription = nil
	}
}

const OpenSessionRequest_WorkspaceDescription_not_set_case case_OpenSessionRequest_WorkspaceDescription = 0
const OpenSessionRequest_Local_case case_OpenSessionRequest_WorkspaceDescription = 2

func (x *OpenSessionRequest) WhichWorkspaceDescription() case_OpenSessionRequest_WorkspaceDescription {
	if x == nil {
		return OpenSessionRequest_WorkspaceDescription_not_set_case
	}
	switch x.xxx_hidden_WorkspaceDescription.(type) {
	case *openSessionRequest_Local:
		return OpenSessionRequest_Local_case
	default:
		return OpenSessionRequest_WorkspaceDescription_not_set_case
	}
}

type OpenSessionRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SessionId *string
	// Fields of oneof xxx_hidden_WorkspaceDescription:
	Local *OpenSessionRequest_WorkspaceDescriptionLocal
	// -- end of xxx_hidden_WorkspaceDescription
}

func (b0 OpenSessionRequest_builder) Build() *OpenSessionRequest {
	m0 := &OpenSessionRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.SessionId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_SessionId = b.SessionId
	}
	if b.Local != nil {
		x.xxx_hidden_WorkspaceDescription = &openSessionRequest_Local{b.Local}
	}
	return m0
}

type case_OpenSessionRequest_WorkspaceDescription protoreflect.FieldNumber

func (x case_OpenSessionRequest_WorkspaceDescription) String() string {
	md := file_bonk_v0_executor_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isOpenSessionRequest_WorkspaceDescription interface {
	isOpenSessionRequest_WorkspaceDescription()
}

type openSessionRequest_Local struct {
	Local *OpenSessionRequest_WorkspaceDescriptionLocal `protobuf:"bytes,2,opt,name=local,oneof"`
}

func (*openSessionRequest_Local) isOpenSessionRequest_WorkspaceDescription() {}

type OpenSessionResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionResponse) Reset() {
	*x = OpenSessionResponse{}
	mi := &file_bonk_v0_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionResponse) ProtoMessage() {}

func (x *OpenSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bonk_v0_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type OpenSessionResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 OpenSessionResponse_builder) Build() *OpenSessionResponse {
	m0 := &OpenSessionResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type CloseSessionRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SessionId   *string                `protobuf:"bytes,1,opt,name=session_id,json=sessionId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_bonk_v0_executor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bonk_v0_executor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		if x.xxx_hidden_SessionId != nil {
			return *x.xxx_hidden_SessionId
		}
		return ""
	}
	return ""
}

func (x *CloseSessionRequest) SetSessionId(v string) {
	x.xxx_hidden_SessionId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *CloseSessionRequest) HasSessionId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CloseSessionRequest) ClearSessionId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_SessionId = nil
}

type CloseSessionRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SessionId *string
}

func (b0 CloseSessionRequest_builder) Build() *CloseSessionRequest {
	m0 := &CloseSessionRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.SessionId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_SessionId = b.SessionId
	}
	return m0
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_bonk_v0_executor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bonk_v0_executor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type CloseSessionResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 CloseSessionResponse_builder) Build() *CloseSessionResponse {
	m0 := &CloseSessionResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ExecuteTaskRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SessionId   *string                `protobuf:"bytes,1,opt,name=session_id,json=sessionId"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Executor    *string                `protobuf:"bytes,3,opt,name=executor"`
	xxx_hidden_Inputs      []string               `protobuf:"bytes,4,rep,name=inputs"`
	xxx_hidden_Parameters  *structpb.Struct       `protobuf:"bytes,5,opt,name=parameters"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ExecuteTaskRequest) Reset() {
	*x = ExecuteTaskRequest{}
	mi := &file_bonk_v0_executor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskRequest) ProtoMessage() {}

func (x *ExecuteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bonk_v0_executor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExecuteTaskRequest) GetSessionId() string {
	if x != nil {
		if x.xxx_hidden_SessionId != nil {
			return *x.xxx_hidden_SessionId
		}
		return ""
	}
	return ""
}

func (x *ExecuteTaskRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *ExecuteTaskRequest) GetExecutor() string {
	if x != nil {
		if x.xxx_hidden_Executor != nil {
			return *x.xxx_hidden_Executor
		}
		return ""
	}
	return ""
}

func (x *ExecuteTaskRequest) GetInputs() []string {
	if x != nil {
		return x.xxx_hidden_Inputs
	}
	return nil
}

func (x *ExecuteTaskRequest) GetParameters() *structpb.Struct {
	if x != nil {
		return x.xxx_hidden_Parameters
	}
	return nil
}

func (x *ExecuteTaskRequest) SetSessionId(v string) {
	x.xxx_hidden_SessionId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *ExecuteTaskRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *ExecuteTaskRequest) SetExecutor(v string) {
	x.xxx_hidden_Executor = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *ExecuteTaskRequest) SetInputs(v []string) {
	x.xxx_hidden_Inputs = v
}

func (x *ExecuteTaskRequest) SetParameters(v *structpb.Struct) {
	x.xxx_hidden_Parameters = v
}

func (x *ExecuteTaskRequest) HasSessionId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ExecuteTaskRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ExecuteTaskRequest) HasExecutor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ExecuteTaskRequest) HasParameters() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Parameters != nil
}

func (x *ExecuteTaskRequest) ClearSessionId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_SessionId = nil
}

func (x *ExecuteTaskRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *ExecuteTaskRequest) ClearExecutor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Executor = nil
}

func (x *ExecuteTaskRequest) ClearParameters() {
	x.xxx_hidden_Parameters = nil
}

type ExecuteTaskRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SessionId  *string
	Name       *string
	Executor   *string
	Inputs     []string
	Parameters *structpb.Struct
}

func (b0 ExecuteTaskRequest_builder) Build() *ExecuteTaskRequest {
	m0 := &ExecuteTaskRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.SessionId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_SessionId = b.SessionId
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Name = b.Name
	}
	if b.Executor != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Executor = b.Executor
	}
	x.xxx_hidden_Inputs = b.Inputs
	x.xxx_hidden_Parameters = b.Parameters
	return m0
}

type ExecuteTaskResponse struct {
	state                    protoimpl.MessageState               `protogen:"opaque.v1"`
	xxx_hidden_Output        []string                             `protobuf:"bytes,1,rep,name=output"`
	xxx_hidden_FollowupTasks *[]*ExecuteTaskResponse_FollowupTask `protobuf:"bytes,2,rep,name=followup_tasks,json=followupTasks"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ExecuteTaskResponse) Reset() {
	*x = ExecuteTaskResponse{}
	mi := &file_bonk_v0_executor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskResponse) ProtoMessage() {}

func (x *ExecuteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bonk_v0_executor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExecuteTaskResponse) GetOutput() []string {
	if x != nil {
		return x.xxx_hidden_Output
	}
	return nil
}

func (x *ExecuteTaskResponse) GetFollowupTasks() []*ExecuteTaskResponse_FollowupTask {
	if x != nil {
		if x.xxx_hidden_FollowupTasks != nil {
			return *x.xxx_hidden_FollowupTasks
		}
	}
	return nil
}

func (x *ExecuteTaskResponse) SetOutput(v []string) {
	x.xxx_hidden_Output = v
}

func (x *ExecuteTaskResponse) SetFollowupTasks(v []*ExecuteTaskResponse_FollowupTask) {
	x.xxx_hidden_FollowupTasks = &v
}

type ExecuteTaskResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Output        []string
	FollowupTasks []*ExecuteTaskResponse_FollowupTask
}

func (b0 ExecuteTaskResponse_builder) Build() *ExecuteTaskResponse {
	m0 := &ExecuteTaskResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Output = b.Output
	x.xxx_hidden_FollowupTasks = &b.FollowupTasks
	return m0
}

type OpenSessionRequest_WorkspaceDescriptionLocal struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AbsolutePath *string                `protobuf:"bytes,1,opt,name=absolute_path,json=absolutePath"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *OpenSessionRequest_WorkspaceDescriptionLocal) Reset() {
	*x = OpenSessionRequest_WorkspaceDescriptionLocal{}
	mi := &file_bonk_v0_executor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionRequest_WorkspaceDescriptionLocal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionRequest_WorkspaceDescriptionLocal) ProtoMessage() {}

func (x *OpenSessionRequest_WorkspaceDescriptionLocal) ProtoReflect() protoreflect.Message {
	mi := &file_bonk_v0_executor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OpenSessionRequest_WorkspaceDescriptionLocal) GetAbsolutePath() string {
	if x != nil {
		if x.xxx_hidden_AbsolutePath != nil {
			return *x.xxx_hidden_AbsolutePath
		}
		return ""
	}
	return ""
}

func (x *OpenSessionRequest_WorkspaceDescriptionLocal) SetAbsolutePath(v string) {
	x.xxx_hidden_AbsolutePath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *OpenSessionRequest_WorkspaceDescriptionLocal) HasAbsolutePath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OpenSessionRequest_WorkspaceDescriptionLocal) ClearAbsolutePath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_AbsolutePath = nil
}

type OpenSessionRequest_WorkspaceDescriptionLocal_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AbsolutePath *string
}

func (b0 OpenSessionRequest_WorkspaceDescriptionLocal_builder) Build() *OpenSessionRequest_WorkspaceDescriptionLocal {
	m0 := &OpenSessionRequest_WorkspaceDescriptionLocal{}
	b, x := &b0, m0
	_, _ = b, x
	if b.AbsolutePath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_AbsolutePath = b.AbsolutePath
	}
	return m0
}

type ExecuteTaskResponse_FollowupTask struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Executor    *string                `protobuf:"bytes,2,opt,name=executor"`
	xxx_hidden_Inputs      []string               `protobuf:"bytes,3,rep,name=inputs"`
	xxx_hidden_Parameters  *structpb.Struct       `protobuf:"bytes,4,opt,name=parameters"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ExecuteTaskResponse_FollowupTask) Reset() {
	*x = ExecuteTaskResponse_FollowupTask{}
	mi := &file_bonk_v0_executor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskResponse_FollowupTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskResponse_FollowupTask) ProtoMessage() {}

func (x *ExecuteTaskResponse_FollowupTask) ProtoReflect() protoreflect.Message {
	mi := &file_bonk_v0_executor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExecuteTaskResponse_FollowupTask) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *ExecuteTaskResponse_FollowupTask) GetExecutor() string {
	if x != nil {
		if x.xxx_hidden_Executor != nil {
			return *x.xxx_hidden_Executor
		}
		return ""
	}
	return ""
}

func (x *ExecuteTaskResponse_FollowupTask) GetInputs() []string {
	if x != nil {
		return x.xxx_hidden_Inputs
	}
	return nil
}

func (x *ExecuteTaskResponse_FollowupTask) GetParameters() *structpb.Struct {
	if x != nil {
		return x.xxx_hidden_Parameters
	}
	return nil
}

func (x *ExecuteTaskResponse_FollowupTask) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *ExecuteTaskResponse_FollowupTask) SetExecutor(v string) {
	x.xxx_hidden_Executor = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *ExecuteTaskResponse_FollowupTask) SetInputs(v []string) {
	x.xxx_hidden_Inputs = v
}

func (x *ExecuteTaskResponse_FollowupTask) SetParameters(v *structpb.Struct) {
	x.xxx_hidden_Parameters = v
}

func (x *ExecuteTaskResponse_FollowupTask) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ExecuteTaskResponse_FollowupTask) HasExecutor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ExecuteTaskResponse_FollowupTask) HasParameters() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Parameters != nil
}

func (x *ExecuteTaskResponse_FollowupTask) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *ExecuteTaskResponse_FollowupTask) ClearExecutor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Executor = nil
}

func (x *ExecuteTaskResponse_FollowupTask) ClearParameters() {
	x.xxx_hidden_Parameters = nil
}

type ExecuteTaskResponse_FollowupTask_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name       *string
	Executor   *string
	Inputs     []string
	Parameters *structpb.Struct
}

func (b0 ExecuteTaskResponse_FollowupTask_builder) Build() *ExecuteTaskResponse_FollowupTask {
	m0 := &ExecuteTaskResponse_FollowupTask{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Name = b.Name
	}
	if b.Executor != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Executor = b.Executor
	}
	x.xxx_hidden_Inputs = b.Inputs
	x.xxx_hidden_Parameters = b.Parameters
	return m0
}

var File_bonk_v0_executor_proto protoreflect.FileDescriptor

const file_bonk_v0_executor_proto_rawDesc = "" +
	"\n" +
	"\x16bonk/v0/executor.proto\x12\abonk.v0\x1a\x1cgoogle/protobuf/struct.proto\"\xdd\x01\n" +
	"\x12OpenSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12M\n" +
	"\x05local\x18\x02 \x01(\v25.bonk.v0.OpenSessionRequest.WorkspaceDescriptionLocalH\x00R\x05local\x1a@\n" +
	"\x19WorkspaceDescriptionLocal\x12#\n" +
	"\rabsolute_path\x18\x01 \x01(\tR\fabsolutePathB\x17\n" +
	"\x15workspace_description\"\x15\n" +
	"\x13OpenSessionResponse\"4\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x16\n" +
	"\x14CloseSessionResponse\"\xb4\x01\n" +
	"\x12ExecuteTaskRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bexecutor\x18\x03 \x01(\tR\bexecutor\x12\x16\n" +
	"\x06inputs\x18\x04 \x03(\tR\x06inputs\x127\n" +
	"\n" +
	"parameters\x18\x05 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\"\x91\x02\n" +
	"\x13ExecuteTaskResponse\x12\x16\n" +
	"\x06output\x18\x01 \x03(\tR\x06output\x12P\n" +
	"\x0efollowup_tasks\x18\x02 \x03(\v2).bonk.v0.ExecuteTaskResponse.FollowupTaskR\rfollowupTasks\x1a\x8f\x01\n" +
	"\fFollowupTask\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bexecutor\x18\x02 \x01(\tR\bexecutor\x12\x16\n" +
	"\x06inputs\x18\x03 \x03(\tR\x06inputs\x127\n" +
	"\n" +
	"parameters\x18\x04 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters2\xf2\x01\n" +
	"\x0fExecutorService\x12H\n" +
	"\vOpenSession\x12\x1b.bonk.v0.OpenSessionRequest\x1a\x1c.bonk.v0.OpenSessionResponse\x12K\n" +
	"\fCloseSession\x12\x1c.bonk.v0.CloseSessionRequest\x1a\x1d.bonk.v0.CloseSessionResponse\x12H\n" +
	"\vExecuteTask\x12\x1b.bonk.v0.ExecuteTaskRequest\x1a\x1c.bonk.v0.ExecuteTaskResponseB}\n" +
	"\vcom.bonk.v0B\rExecutorProtoP\x01Z\"go.bonk.build/api/go/proto/bonk/v0\xa2\x02\x03BVX\xaa\x02\aBonk.V0\xca\x02\aBonk\\V0\xe2\x02\x13Bonk\\V0\\GPBMetadata\xea\x02\bBonk::V0b\beditionsp\xe8\a"

var file_bonk_v0_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_bonk_v0_executor_proto_goTypes = []any{
	(*OpenSessionRequest)(nil),                           // 0: bonk.v0.OpenSessionRequest
	(*OpenSessionResponse)(nil),                          // 1: bonk.v0.OpenSessionResponse
	(*CloseSessionRequest)(nil),                          // 2: bonk.v0.CloseSessionRequest
	(*CloseSessionResponse)(nil),                         // 3: bonk.v0.CloseSessionResponse
	(*ExecuteTaskRequest)(nil),                           // 4: bonk.v0.ExecuteTaskRequest
	(*ExecuteTaskResponse)(nil),                          // 5: bonk.v0.ExecuteTaskResponse
	(*OpenSessionRequest_WorkspaceDescriptionLocal)(nil), // 6: bonk.v0.OpenSessionRequest.WorkspaceDescriptionLocal
	(*ExecuteTaskResponse_FollowupTask)(nil),             // 7: bonk.v0.ExecuteTaskResponse.FollowupTask
	(*structpb.Struct)(nil),                              // 8: google.protobuf.Struct
}
var file_bonk_v0_executor_proto_depIdxs = []int32{
	6, // 0: bonk.v0.OpenSessionRequest.local:type_name -> bonk.v0.OpenSessionRequest.WorkspaceDescriptionLocal
	8, // 1: bonk.v0.ExecuteTaskRequest.parameters:type_name -> google.protobuf.Struct
	7, // 2: bonk.v0.ExecuteTaskResponse.followup_tasks:type_name -> bonk.v0.ExecuteTaskResponse.FollowupTask
	8, // 3: bonk.v0.ExecuteTaskResponse.FollowupTask.parameters:type_name -> google.protobuf.Struct
	0, // 4: bonk.v0.ExecutorService.OpenSession:input_type -> bonk.v0.OpenSessionRequest
	2, // 5: bonk.v0.ExecutorService.CloseSession:input_type -> bonk.v0.CloseSessionRequest
	4, // 6: bonk.v0.ExecutorService.ExecuteTask:input_type -> bonk.v0.ExecuteTaskRequest
	1, // 7: bonk.v0.ExecutorService.OpenSession:output_type -> bonk.v0.OpenSessionResponse
	3, // 8: bonk.v0.ExecutorService.CloseSession:output_type -> bonk.v0.CloseSessionResponse
	5, // 9: bonk.v0.ExecutorService.ExecuteTask:output_type -> bonk.v0.ExecuteTaskResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_bonk_v0_executor_proto_init() }
func file_bonk_v0_executor_proto_init() {
	if File_bonk_v0_executor_proto != nil {
		return
	}
	file_bonk_v0_executor_proto_msgTypes[0].OneofWrappers = []any{
		(*openSessionRequest_Local)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bonk_v0_executor_proto_rawDesc), len(file_bonk_v0_executor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bonk_v0_executor_proto_goTypes,
		DependencyIndexes: file_bonk_v0_executor_proto_depIdxs,
		MessageInfos:      file_bonk_v0_executor_proto_msgTypes,
	}.Build()
	File_bonk_v0_executor_proto = out.File
	file_bonk_v0_executor_proto_goTypes = nil
	file_bonk_v0_executor_proto_depIdxs = nil
}
