// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: bonk/v0/log_streaming.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamLogsRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Level       int64                  `protobuf:"varint,1,opt,name=level"`
	xxx_hidden_AddSource   bool                   `protobuf:"varint,2,opt,name=add_source,json=addSource"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_bonk_v0_log_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bonk_v0_log_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamLogsRequest) GetLevel() int64 {
	if x != nil {
		return x.xxx_hidden_Level
	}
	return 0
}

func (x *StreamLogsRequest) GetAddSource() bool {
	if x != nil {
		return x.xxx_hidden_AddSource
	}
	return false
}

func (x *StreamLogsRequest) SetLevel(v int64) {
	x.xxx_hidden_Level = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *StreamLogsRequest) SetAddSource(v bool) {
	x.xxx_hidden_AddSource = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *StreamLogsRequest) HasLevel() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StreamLogsRequest) HasAddSource() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StreamLogsRequest) ClearLevel() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Level = 0
}

func (x *StreamLogsRequest) ClearAddSource() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_AddSource = false
}

type StreamLogsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Level     *int64
	AddSource *bool
}

func (b0 StreamLogsRequest_builder) Build() *StreamLogsRequest {
	m0 := &StreamLogsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Level != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Level = *b.Level
	}
	if b.AddSource != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_AddSource = *b.AddSource
	}
	return m0
}

// This is meant to mirror [slog.Record](https://pkg.go.dev/log/slog#Record)
type StreamLogsResponse struct {
	state                  protoimpl.MessageState     `protogen:"opaque.v1"`
	xxx_hidden_Time        *timestamppb.Timestamp     `protobuf:"bytes,1,opt,name=time"`
	xxx_hidden_Message     *string                    `protobuf:"bytes,2,opt,name=message"`
	xxx_hidden_Level       int64                      `protobuf:"varint,3,opt,name=level"`
	xxx_hidden_Attrs       map[string]*structpb.Value `protobuf:"bytes,4,rep,name=attrs" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StreamLogsResponse) Reset() {
	*x = StreamLogsResponse{}
	mi := &file_bonk_v0_log_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsResponse) ProtoMessage() {}

func (x *StreamLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bonk_v0_log_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamLogsResponse) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Time
	}
	return nil
}

func (x *StreamLogsResponse) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *StreamLogsResponse) GetLevel() int64 {
	if x != nil {
		return x.xxx_hidden_Level
	}
	return 0
}

func (x *StreamLogsResponse) GetAttrs() map[string]*structpb.Value {
	if x != nil {
		return x.xxx_hidden_Attrs
	}
	return nil
}

func (x *StreamLogsResponse) SetTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_Time = v
}

func (x *StreamLogsResponse) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *StreamLogsResponse) SetLevel(v int64) {
	x.xxx_hidden_Level = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *StreamLogsResponse) SetAttrs(v map[string]*structpb.Value) {
	x.xxx_hidden_Attrs = v
}

func (x *StreamLogsResponse) HasTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Time != nil
}

func (x *StreamLogsResponse) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StreamLogsResponse) HasLevel() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *StreamLogsResponse) ClearTime() {
	x.xxx_hidden_Time = nil
}

func (x *StreamLogsResponse) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

func (x *StreamLogsResponse) ClearLevel() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Level = 0
}

type StreamLogsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Time    *timestamppb.Timestamp
	Message *string
	Level   *int64
	Attrs   map[string]*structpb.Value
}

func (b0 StreamLogsResponse_builder) Build() *StreamLogsResponse {
	m0 := &StreamLogsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Time = b.Time
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Message = b.Message
	}
	if b.Level != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Level = *b.Level
	}
	x.xxx_hidden_Attrs = b.Attrs
	return m0
}

var File_bonk_v0_log_streaming_proto protoreflect.FileDescriptor

const file_bonk_v0_log_streaming_proto_rawDesc = "" +
	"\n" +
	"\x1bbonk/v0/log_streaming.proto\x12\abonk.v0\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"H\n" +
	"\x11StreamLogsRequest\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x03R\x05level\x12\x1d\n" +
	"\n" +
	"add_source\x18\x02 \x01(\bR\taddSource\"\x84\x02\n" +
	"\x12StreamLogsResponse\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x03R\x05level\x12<\n" +
	"\x05attrs\x18\x04 \x03(\v2&.bonk.v0.StreamLogsResponse.AttrsEntryR\x05attrs\x1aP\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x012^\n" +
	"\x13LogStreamingService\x12G\n" +
	"\n" +
	"StreamLogs\x12\x1a.bonk.v0.StreamLogsRequest\x1a\x1b.bonk.v0.StreamLogsResponse0\x01B\x81\x01\n" +
	"\vcom.bonk.v0B\x11LogStreamingProtoP\x01Z\"go.bonk.build/api/go/proto/bonk/v0\xa2\x02\x03BVX\xaa\x02\aBonk.V0\xca\x02\aBonk\\V0\xe2\x02\x13Bonk\\V0\\GPBMetadata\xea\x02\bBonk::V0b\beditionsp\xe8\a"

var file_bonk_v0_log_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bonk_v0_log_streaming_proto_goTypes = []any{
	(*StreamLogsRequest)(nil),     // 0: bonk.v0.StreamLogsRequest
	(*StreamLogsResponse)(nil),    // 1: bonk.v0.StreamLogsResponse
	nil,                           // 2: bonk.v0.StreamLogsResponse.AttrsEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*structpb.Value)(nil),        // 4: google.protobuf.Value
}
var file_bonk_v0_log_streaming_proto_depIdxs = []int32{
	3, // 0: bonk.v0.StreamLogsResponse.time:type_name -> google.protobuf.Timestamp
	2, // 1: bonk.v0.StreamLogsResponse.attrs:type_name -> bonk.v0.StreamLogsResponse.AttrsEntry
	4, // 2: bonk.v0.StreamLogsResponse.AttrsEntry.value:type_name -> google.protobuf.Value
	0, // 3: bonk.v0.LogStreamingService.StreamLogs:input_type -> bonk.v0.StreamLogsRequest
	1, // 4: bonk.v0.LogStreamingService.StreamLogs:output_type -> bonk.v0.StreamLogsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bonk_v0_log_streaming_proto_init() }
func file_bonk_v0_log_streaming_proto_init() {
	if File_bonk_v0_log_streaming_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bonk_v0_log_streaming_proto_rawDesc), len(file_bonk_v0_log_streaming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bonk_v0_log_streaming_proto_goTypes,
		DependencyIndexes: file_bonk_v0_log_streaming_proto_depIdxs,
		MessageInfos:      file_bonk_v0_log_streaming_proto_msgTypes,
	}.Build()
	File_bonk_v0_log_streaming_proto = out.File
	file_bonk_v0_log_streaming_proto_goTypes = nil
	file_bonk_v0_log_streaming_proto_depIdxs = nil
}
