// Copyright © 2025 Colden Cullen
// SPDX-License-Identifier: MIT

// Code generated by MockGen. DO NOT EDIT.
// Source: go.bonk.build/pkg/task (interfaces: Executor,TypedExecutor)
//
// Generated by this command:
//
//	mockgen -destination executor_mock.go -package task -copyright_file ../../license-header.txt -typed . Executor,TypedExecutor
//

// Package task is a generated GoMock package.
package task

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExecutor is a mock of Executor interface.
type MockExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorMockRecorder
	isgomock struct{}
}

// MockExecutorMockRecorder is the mock recorder for MockExecutor.
type MockExecutorMockRecorder struct {
	mock *MockExecutor
}

// NewMockExecutor creates a new mock instance.
func NewMockExecutor(ctrl *gomock.Controller) *MockExecutor {
	mock := &MockExecutor{ctrl: ctrl}
	mock.recorder = &MockExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutor) EXPECT() *MockExecutorMockRecorder {
	return m.recorder
}

// CloseSession mocks base method.
func (m *MockExecutor) CloseSession(ctx context.Context, sessionId SessionId) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseSession", ctx, sessionId)
}

// CloseSession indicates an expected call of CloseSession.
func (mr *MockExecutorMockRecorder) CloseSession(ctx, sessionId any) *MockExecutorCloseSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSession", reflect.TypeOf((*MockExecutor)(nil).CloseSession), ctx, sessionId)
	return &MockExecutorCloseSessionCall{Call: call}
}

// MockExecutorCloseSessionCall wrap *gomock.Call
type MockExecutorCloseSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutorCloseSessionCall) Return() *MockExecutorCloseSessionCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutorCloseSessionCall) Do(f func(context.Context, SessionId)) *MockExecutorCloseSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutorCloseSessionCall) DoAndReturn(f func(context.Context, SessionId)) *MockExecutorCloseSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Execute mocks base method.
func (m *MockExecutor) Execute(ctx context.Context, tsk *Task, result *Result) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, tsk, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockExecutorMockRecorder) Execute(ctx, tsk, result any) *MockExecutorExecuteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockExecutor)(nil).Execute), ctx, tsk, result)
	return &MockExecutorExecuteCall{Call: call}
}

// MockExecutorExecuteCall wrap *gomock.Call
type MockExecutorExecuteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutorExecuteCall) Return(arg0 error) *MockExecutorExecuteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutorExecuteCall) Do(f func(context.Context, *Task, *Result) error) *MockExecutorExecuteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutorExecuteCall) DoAndReturn(f func(context.Context, *Task, *Result) error) *MockExecutorExecuteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// OpenSession mocks base method.
func (m *MockExecutor) OpenSession(ctx context.Context, session Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// OpenSession indicates an expected call of OpenSession.
func (mr *MockExecutorMockRecorder) OpenSession(ctx, session any) *MockExecutorOpenSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenSession", reflect.TypeOf((*MockExecutor)(nil).OpenSession), ctx, session)
	return &MockExecutorOpenSessionCall{Call: call}
}

// MockExecutorOpenSessionCall wrap *gomock.Call
type MockExecutorOpenSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutorOpenSessionCall) Return(arg0 error) *MockExecutorOpenSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutorOpenSessionCall) Do(f func(context.Context, Session) error) *MockExecutorOpenSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutorOpenSessionCall) DoAndReturn(f func(context.Context, Session) error) *MockExecutorOpenSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockTypedExecutor is a mock of TypedExecutor interface.
type MockTypedExecutor[Params any] struct {
	ctrl     *gomock.Controller
	recorder *MockTypedExecutorMockRecorder[Params]
	isgomock struct{}
}

// MockTypedExecutorMockRecorder is the mock recorder for MockTypedExecutor.
type MockTypedExecutorMockRecorder[Params any] struct {
	mock *MockTypedExecutor[Params]
}

// NewMockTypedExecutor creates a new mock instance.
func NewMockTypedExecutor[Params any](ctrl *gomock.Controller) *MockTypedExecutor[Params] {
	mock := &MockTypedExecutor[Params]{ctrl: ctrl}
	mock.recorder = &MockTypedExecutorMockRecorder[Params]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTypedExecutor[Params]) EXPECT() *MockTypedExecutorMockRecorder[Params] {
	return m.recorder
}

// CloseSession mocks base method.
func (m *MockTypedExecutor[Params]) CloseSession(ctx context.Context, sessionId SessionId) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseSession", ctx, sessionId)
}

// CloseSession indicates an expected call of CloseSession.
func (mr *MockTypedExecutorMockRecorder[Params]) CloseSession(ctx, sessionId any) *MockTypedExecutorCloseSessionCall[Params] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSession", reflect.TypeOf((*MockTypedExecutor[Params])(nil).CloseSession), ctx, sessionId)
	return &MockTypedExecutorCloseSessionCall[Params]{Call: call}
}

// MockTypedExecutorCloseSessionCall wrap *gomock.Call
type MockTypedExecutorCloseSessionCall[Params any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTypedExecutorCloseSessionCall[Params]) Return() *MockTypedExecutorCloseSessionCall[Params] {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTypedExecutorCloseSessionCall[Params]) Do(f func(context.Context, SessionId)) *MockTypedExecutorCloseSessionCall[Params] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTypedExecutorCloseSessionCall[Params]) DoAndReturn(f func(context.Context, SessionId)) *MockTypedExecutorCloseSessionCall[Params] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Execute mocks base method.
func (m *MockTypedExecutor[Params]) Execute(ctx context.Context, tsk *Task, args *Params, result *Result) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, tsk, args, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockTypedExecutorMockRecorder[Params]) Execute(ctx, tsk, args, result any) *MockTypedExecutorExecuteCall[Params] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockTypedExecutor[Params])(nil).Execute), ctx, tsk, args, result)
	return &MockTypedExecutorExecuteCall[Params]{Call: call}
}

// MockTypedExecutorExecuteCall wrap *gomock.Call
type MockTypedExecutorExecuteCall[Params any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTypedExecutorExecuteCall[Params]) Return(arg0 error) *MockTypedExecutorExecuteCall[Params] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTypedExecutorExecuteCall[Params]) Do(f func(context.Context, *Task, *Params, *Result) error) *MockTypedExecutorExecuteCall[Params] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTypedExecutorExecuteCall[Params]) DoAndReturn(f func(context.Context, *Task, *Params, *Result) error) *MockTypedExecutorExecuteCall[Params] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// OpenSession mocks base method.
func (m *MockTypedExecutor[Params]) OpenSession(ctx context.Context, session Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// OpenSession indicates an expected call of OpenSession.
func (mr *MockTypedExecutorMockRecorder[Params]) OpenSession(ctx, session any) *MockTypedExecutorOpenSessionCall[Params] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenSession", reflect.TypeOf((*MockTypedExecutor[Params])(nil).OpenSession), ctx, session)
	return &MockTypedExecutorOpenSessionCall[Params]{Call: call}
}

// MockTypedExecutorOpenSessionCall wrap *gomock.Call
type MockTypedExecutorOpenSessionCall[Params any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTypedExecutorOpenSessionCall[Params]) Return(arg0 error) *MockTypedExecutorOpenSessionCall[Params] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTypedExecutorOpenSessionCall[Params]) Do(f func(context.Context, Session) error) *MockTypedExecutorOpenSessionCall[Params] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTypedExecutorOpenSessionCall[Params]) DoAndReturn(f func(context.Context, Session) error) *MockTypedExecutorOpenSessionCall[Params] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
