# Copyright © 2025 Colden Cullen
# SPDX-License-Identifier: MIT

codecov:
  branch: main

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

ignore:
- api
- cmd
- "**/*_mock.go"
