# Copyright © 2025 Colden Cullen
# SPDX-License-Identifier: MIT

format: github
output: ./docs/api/go.md
package: go.bonk.build/api/go
repository:
  url: https://github.com/bonk-build/bonk
  defaultBranch: main
