# Copyright © 2025 Colden Cullen
# SPDX-License-Identifier: MIT

[settings]
experimental = true
all_compile = false

[env]
CGO_ENABLED = 1

[tools]
# Build tools
go = "1.26.1"
buf = "1.67.0"
"github:vektra/mockery" = "3.7.0"
# Developer tools
prek = "0.3.5"
golangci-lint = "2.11.4"
"github:korandoru/hawkeye" = "6.5.1"

[tasks]
generate.run = "go generate ./..."
build.run = "go build ./..."
test.run = "go test ./... -race -count 100 -parallel 8"
lint.run = ["golangci-lint fmt", "golangci-lint run", "hawkeye format"]
