# Copyright © 2025 Colden Cullen
# SPDX-License-Identifier: MIT

[settings]
experimental = true
all_compile = false

[tools]
# Build tools
buf = "1.72.0"
# Developer tools
"github:korandoru/hawkeye" = "latest"
"cargo:cargo-nextest" = "latest"

[tasks]
build.run = "cargo build"
test.run = "cargo nextest run"
lint.run = ["cargo fmt", "cargo clippy", "hawkeye check"]
