# Copyright © 2025 Colden Cullen

inlineHeader = "Copyright © 2025 Colden Cullen"

excludes = ["*.lock", "*.sum"]

[mapping.DOUBLESLASH_STYLE]
extensions = ["go", "cue"]

[mapping.SCRIPT_STYLE]
extensions = ["nix"]

[properties]
inceptionYear = 2025
