# Copyright © 2025 Colden Cullen
# SPDX-License-Identifier: MIT

headerPath = "license-header.txt"

excludes = ["*.lock", "*.sum", "*.pb.go"]

[mapping.DOUBLESLASH_STYLE]
extensions = ["go", "cue", "proto"]

[mapping.SCRIPT_STYLE]
extensions = ["nix"]

[properties]
inceptionYear = 2025
