# Copyright © 2025 Colden Cullen
# SPDX-License-Identifier: MIT

site_name: Bonk
site_url: https://bonk.build/
repo_url: https://github.com/bonk-build/bonk
repo_name: bonk-build/bonk

theme:
  name: material
  logo: assets/bonk.png
  favicon: assets/bonk.png
  palette:
    - media: "(prefers-color-scheme: dark)"
      toggle:
        name: dark
        icon: material/brightness-4
      scheme: slate
      primary: red

    - media: "(prefers-color-scheme: light)"
      toggle:
        name: light
        icon: material/brightness-7
      scheme: default
      primary: red

plugins:
  - mike:
      canonical_version: latest
      version_selector: true

extra:
  version:
    provider: mike
    alias: true

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - markdown.extensions.tables
  - pymdownx.inlinehilite
  - sane_lists
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

strict: true
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
