// Copyright © 2025 Colden Cullen
// SPDX-License-Identifier: MIT

// Code generated by MockGen. DO NOT EDIT.
// Source: go.bonk.build/pkg/executor (interfaces: Executor,SessionManager)
//
// Generated by this command:
//
//	mockgen -destination executor_mock_test.go -package executor_test -copyright_file ../../license-header.txt -typed . Executor,SessionManager
//

// Package executor_test is a generated GoMock package.
package executor_test

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	task "go.bonk.build/pkg/task"
	gomock "go.uber.org/mock/gomock"
)

// MockExecutor is a mock of Executor interface.
type MockExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorMockRecorder
	isgomock struct{}
}

// MockExecutorMockRecorder is the mock recorder for MockExecutor.
type MockExecutorMockRecorder struct {
	mock *MockExecutor
}

// NewMockExecutor creates a new mock instance.
func NewMockExecutor(ctrl *gomock.Controller) *MockExecutor {
	mock := &MockExecutor{ctrl: ctrl}
	mock.recorder = &MockExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutor) EXPECT() *MockExecutorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockExecutor) Execute(ctx context.Context, tsk task.Task, result *task.Result) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, tsk, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockExecutorMockRecorder) Execute(ctx, tsk, result any) *MockExecutorExecuteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockExecutor)(nil).Execute), ctx, tsk, result)
	return &MockExecutorExecuteCall{Call: call}
}

// MockExecutorExecuteCall wrap *gomock.Call
type MockExecutorExecuteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutorExecuteCall) Return(arg0 error) *MockExecutorExecuteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutorExecuteCall) Do(f func(context.Context, task.Task, *task.Result) error) *MockExecutorExecuteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutorExecuteCall) DoAndReturn(f func(context.Context, task.Task, *task.Result) error) *MockExecutorExecuteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Name mocks base method.
func (m *MockExecutor) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockExecutorMockRecorder) Name() *MockExecutorNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockExecutor)(nil).Name))
	return &MockExecutorNameCall{Call: call}
}

// MockExecutorNameCall wrap *gomock.Call
type MockExecutorNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutorNameCall) Return(arg0 string) *MockExecutorNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutorNameCall) Do(f func() string) *MockExecutorNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutorNameCall) DoAndReturn(f func() string) *MockExecutorNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSessionManager is a mock of SessionManager interface.
type MockSessionManager struct {
	ctrl     *gomock.Controller
	recorder *MockSessionManagerMockRecorder
	isgomock struct{}
}

// MockSessionManagerMockRecorder is the mock recorder for MockSessionManager.
type MockSessionManagerMockRecorder struct {
	mock *MockSessionManager
}

// NewMockSessionManager creates a new mock instance.
func NewMockSessionManager(ctrl *gomock.Controller) *MockSessionManager {
	mock := &MockSessionManager{ctrl: ctrl}
	mock.recorder = &MockSessionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionManager) EXPECT() *MockSessionManagerMockRecorder {
	return m.recorder
}

// CloseSession mocks base method.
func (m *MockSessionManager) CloseSession(ctx context.Context, sessionId uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseSession", ctx, sessionId)
}

// CloseSession indicates an expected call of CloseSession.
func (mr *MockSessionManagerMockRecorder) CloseSession(ctx, sessionId any) *MockSessionManagerCloseSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSession", reflect.TypeOf((*MockSessionManager)(nil).CloseSession), ctx, sessionId)
	return &MockSessionManagerCloseSessionCall{Call: call}
}

// MockSessionManagerCloseSessionCall wrap *gomock.Call
type MockSessionManagerCloseSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionManagerCloseSessionCall) Return() *MockSessionManagerCloseSessionCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionManagerCloseSessionCall) Do(f func(context.Context, uuid.UUID)) *MockSessionManagerCloseSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionManagerCloseSessionCall) DoAndReturn(f func(context.Context, uuid.UUID)) *MockSessionManagerCloseSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// OpenSession mocks base method.
func (m *MockSessionManager) OpenSession(ctx context.Context, session task.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// OpenSession indicates an expected call of OpenSession.
func (mr *MockSessionManagerMockRecorder) OpenSession(ctx, session any) *MockSessionManagerOpenSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenSession", reflect.TypeOf((*MockSessionManager)(nil).OpenSession), ctx, session)
	return &MockSessionManagerOpenSessionCall{Call: call}
}

// MockSessionManagerOpenSessionCall wrap *gomock.Call
type MockSessionManagerOpenSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionManagerOpenSessionCall) Return(arg0 error) *MockSessionManagerOpenSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionManagerOpenSessionCall) Do(f func(context.Context, task.Session) error) *MockSessionManagerOpenSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionManagerOpenSessionCall) DoAndReturn(f func(context.Context, task.Session) error) *MockSessionManagerOpenSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
