// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package argconv

import (
	"context"
	mock "github.com/stretchr/testify/mock"
	"go.bonk.build/pkg/task"
)

// NewMockTypedExecutor creates a new instance of MockTypedExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTypedExecutor[Params any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTypedExecutor[Params] {
	mock := &MockTypedExecutor[Params]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTypedExecutor is an autogenerated mock type for the TypedExecutor type
type MockTypedExecutor[Params any] struct {
	mock.Mock
}

type MockTypedExecutor_Expecter[Params any] struct {
	mock *mock.Mock
}

func (_m *MockTypedExecutor[Params]) EXPECT() *MockTypedExecutor_Expecter[Params] {
	return &MockTypedExecutor_Expecter[Params]{mock: &_m.Mock}
}

// CloseSession provides a mock function for the type MockTypedExecutor
func (_mock *MockTypedExecutor[Params]) CloseSession(ctx context.Context, sessionID task.SessionID) {
	_mock.Called(ctx, sessionID)
	return
}

// MockTypedExecutor_CloseSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseSession'
type MockTypedExecutor_CloseSession_Call[Params any] struct {
	*mock.Call
}

// CloseSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID task.SessionID
func (_e *MockTypedExecutor_Expecter[Params]) CloseSession(ctx interface{}, sessionID interface{}) *MockTypedExecutor_CloseSession_Call[Params] {
	return &MockTypedExecutor_CloseSession_Call[Params]{Call: _e.mock.On("CloseSession", ctx, sessionID)}
}

func (_c *MockTypedExecutor_CloseSession_Call[Params]) Run(run func(ctx context.Context, sessionID task.SessionID)) *MockTypedExecutor_CloseSession_Call[Params] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 task.SessionID
		if args[1] != nil {
			arg1 = args[1].(task.SessionID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTypedExecutor_CloseSession_Call[Params]) Return() *MockTypedExecutor_CloseSession_Call[Params] {
	_c.Call.Return()
	return _c
}

func (_c *MockTypedExecutor_CloseSession_Call[Params]) RunAndReturn(run func(ctx context.Context, sessionID task.SessionID)) *MockTypedExecutor_CloseSession_Call[Params] {
	_c.Run(run)
	return _c
}

// Execute provides a mock function for the type MockTypedExecutor
func (_mock *MockTypedExecutor[Params]) Execute(ctx context.Context, session task.Session, tsk *task.Task, args *Params, result *task.Result) error {
	ret := _mock.Called(ctx, session, tsk, args, result)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, task.Session, *task.Task, *Params, *task.Result) error); ok {
		r0 = returnFunc(ctx, session, tsk, args, result)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTypedExecutor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockTypedExecutor_Execute_Call[Params any] struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - session task.Session
//   - tsk *task.Task
//   - args *Params
//   - result *task.Result
func (_e *MockTypedExecutor_Expecter[Params]) Execute(ctx interface{}, session interface{}, tsk interface{}, args interface{}, result interface{}) *MockTypedExecutor_Execute_Call[Params] {
	return &MockTypedExecutor_Execute_Call[Params]{Call: _e.mock.On("Execute", ctx, session, tsk, args, result)}
}

func (_c *MockTypedExecutor_Execute_Call[Params]) Run(run func(ctx context.Context, session task.Session, tsk *task.Task, args *Params, result *task.Result)) *MockTypedExecutor_Execute_Call[Params] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 task.Session
		if args[1] != nil {
			arg1 = args[1].(task.Session)
		}
		var arg2 *task.Task
		if args[2] != nil {
			arg2 = args[2].(*task.Task)
		}
		var arg3 *Params
		if args[3] != nil {
			arg3 = args[3].(*Params)
		}
		var arg4 *task.Result
		if args[4] != nil {
			arg4 = args[4].(*task.Result)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTypedExecutor_Execute_Call[Params]) Return(err error) *MockTypedExecutor_Execute_Call[Params] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTypedExecutor_Execute_Call[Params]) RunAndReturn(run func(ctx context.Context, session task.Session, tsk *task.Task, args *Params, result *task.Result) error) *MockTypedExecutor_Execute_Call[Params] {
	_c.Call.Return(run)
	return _c
}

// OpenSession provides a mock function for the type MockTypedExecutor
func (_mock *MockTypedExecutor[Params]) OpenSession(ctx context.Context, session task.Session) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for OpenSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, task.Session) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTypedExecutor_OpenSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenSession'
type MockTypedExecutor_OpenSession_Call[Params any] struct {
	*mock.Call
}

// OpenSession is a helper method to define mock.On call
//   - ctx context.Context
//   - session task.Session
func (_e *MockTypedExecutor_Expecter[Params]) OpenSession(ctx interface{}, session interface{}) *MockTypedExecutor_OpenSession_Call[Params] {
	return &MockTypedExecutor_OpenSession_Call[Params]{Call: _e.mock.On("OpenSession", ctx, session)}
}

func (_c *MockTypedExecutor_OpenSession_Call[Params]) Run(run func(ctx context.Context, session task.Session)) *MockTypedExecutor_OpenSession_Call[Params] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 task.Session
		if args[1] != nil {
			arg1 = args[1].(task.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTypedExecutor_OpenSession_Call[Params]) Return(err error) *MockTypedExecutor_OpenSession_Call[Params] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTypedExecutor_OpenSession_Call[Params]) RunAndReturn(run func(ctx context.Context, session task.Session) error) *MockTypedExecutor_OpenSession_Call[Params] {
	_c.Call.Return(run)
	return _c
}
