# Copyright © 2025 Colden Cullen
# SPDX-License-Identifier: MIT

name: build
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.work

      - name: go build
        run: go build ./...
