# Copyright © 2025 Colden Cullen
# SPDX-License-Identifier: MIT

name: docs
on:
  push: {}
  release:
    types:
      - published

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ssh-key: ${{ secrets.DOCS_DEPLOY_KEY }}
      - uses: fregante/setup-git-user@024bc0b8e177d7e77203b48dab6fb45666854b35 # v2.0.2
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        id: setup-python
        with:
          python-version: 3.13
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod

      - run: git fetch origin gh-pages

      - name: install mkdocs
        if: steps.pipx-cache.outputs.cache-hit != 'true'
        run: pip install mkdocs mike mkdocs-material

      - name: generate cmd docs
        run: go run -tags docs ./cmd/cuebe docs

      - name: generate go api docs
        run: go tool gomarkdoc github.com/dislogical/cuebe/api/go

      - name: commit generated docs
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6.0.1
        with:
          commit_message: "docs: generate cmd docs"
          file_pattern: ./docs/cmd/*.md
          add_options: --all

      - name: publish docs
        if: github.ref_name == 'main'
        run: mike deploy --push main

      - name: publish release
        if: startsWith(github.ref, 'refs/tags/v')
        run: mike deploy --push --update-aliases ${{ github.ref_name }} latest
