# Copyright © 2025 Colden Cullen
# SPDX-License-Identifier: MIT

name: push
on:
  - push
permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      security-events: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          experimental: true

      - uses: j178/prek-action@5337cb91e0fa35a7ff31b9ca345126d8bbbcdf16 # v2.0.6
        env:
          PREK_SKIP: no-commit-to-branch,hawkeye-format,buf-lint,buf-format,zizmor

      - run: hawkeye check

      - name: buf build
        uses: bufbuild/buf-action@8c6a16e16f12ba20b6470afa9c2ba9b5ba8c97c3 # v1.5.0
        with:
          lint: true
          format: true
          push: false

      - name: zizmor
        uses: zizmorcore/zizmor-action@629d5d01fe5939a6aeae25c1bd1acd2cfa28e9b2

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          experimental: true

      - name: build
        run: mise run build

      - name: go test
        run: 'go tool gotestsum
          --packages="./..."
          --junitfile junit.xml
          --
          -coverprofile=coverage.txt
          -race
          -count 100
          -parallel "$(nproc)"'

      - name: upload coverage reports to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt

      - name: upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@0fa95f0e1eeaafde2c782583b36b28ad0d8c77d3 # v1.2.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./junit.xml

  deploy-docs:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      deployments: write

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          experimental: true
          cache: false

      - name: install zensical
        run: pipx install zensical

      - name: build docs
        run: zensical build

      - name: deploy pages
        uses: cloudflare/wrangler-action@9acf94ace14e7dc412b076f2c5c20b8ce93c79cd # v3.15.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_DEPLOY_TOKEN }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy site --project-name=bonk-build --branch=${{ github.head_ref || github.ref_name }}
